[project]
name = "django-backend"

[plugins]
  postgresql = {}

[build]
# Commandes exécutées lors du déploiement
commands = [
  "pip install -r requirements.txt",
  "python manage.py check --database default",
  "python manage.py makemigrations",
  "python manage.py makemigrations hackathon",
  "python manage.py migrate",
  '''echo "from django.contrib.auth.models import User; User.objects.create_superuser('yoann', 'yoann@example.com', 'admin') if not User.objects.filter(username='yoann').exists() else print('Superuser already exists')" | python manage.py shell'''
]

[start]
# Commande pour démarrer le serveur
command = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
