[project]
name = "django-backend"

[plugins]
  postgresql = {}

[build]
# Commandes exécutées lors du déploiement
commands = [
  ]

[start]
# Commande pour démarrer le serveur
command = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
